pullRequestOpened: >
  Acabas de iniciar un pull request para integrar los cambios que has ido realizando en tu branch personal, ¡bien! :thumbsup:


  Recuerda asignar los metadatos correctamente (a la derecha):


  - En **Reviewers**, selecciona a la persona encargada de Control durante esta unidad

  - En **Asignees**, indica quiénes necesitas que intervengan en la conversación (puedes incluir también a la profesora humana si tenéis dudas)

  - En **Milestones**, asigna este pull request al borrador correspondiente (_Estrategia_, _Alcance_, _Estructura_, _Esqueleto_, _Superficie_).


  Ahora podéis realizar los comentarios necesarios sobre estas modificaciones aquí debajo, y tú puedes seguir realizando cambios a tu branch personal. Cuando la persona encargada de Control considere que esta aportación está como para integrar en el borrador, puede aprobar los cambios, y entonces la persona encargada de la Coordinación podrá hacer merge e integrar las modificaciones en el branch `master`.


  Como siempre, si tenéis dudas, mencionad a Miren.