addCollaborators:
  newCollaboratorMessage: "¡Hola! Soy el :robot: asistente de este repositorio (puedes llamarme El Robot).\n\n Me alegro de verte por aquí :wave:. Supongo que sabes lo que estás haciendo, así que voy a añadirte como usuario colaborador. Esto te dará permisos para hacer commits en este repositorio."
  existingCollaboratorMessage: ""
remindMerge:
  merged: ":tada: ¡Enhorabuena! Habéis integrado los cambios de alguien en el branch principal `master`.\n\nAhora tenéis algunas tareas que hacer:\n\n- Ahora que ya habéis integrado los cambios, podéis eliminar el branch donde se han ido generando. Simplemente haced clic en el botón `Delete branch` aquí abajo y se borrará el branch en la copia online.\n- El branch principal `master` ahora ha cambiado (con los cambios que acabáis de integrar). Acordaos de actualizar todas vuestras copias locales (tenéis [instrucciones](https://deustopweb2018.github.io/actualizar-fork.html) si os hacen falta).\n\nSi éste era el último PR que quedaba por integrar antes de la entrega... significa que ya habéis terminado de realizar aportaciones a este borrador :sparkles: \n\n :construction: La persona de Comunicación debe generar el release y formalizar la entrega del apartado vía ALUD (_paso a paso_ en el documento de instrucciones). :construction:"
  unmerged: ":poop: Oops, parece que habéis cerrado este PR sin hacer merge. ¿Ha pasado algo?\n\nAunque el contenido no esté en condiciones de incorporar todavía, podéis continuar haciendo modificaciones (commits) en este branch (aparecerán en la lista de actividad en esta misma página), y combinarlos cuando estén listos.\n\nNo dudéis en pedir ayuda a mi versión humana (mencionadla con @) si necesitáis ayuda con algo."
checkExtension:
  name: ""
  extension: ""
  detailsURL: ""
  success: ""
  failure: ""
checkPath:
  name: ""
  path: ""
  detailsURL: ""
  success: ""
  failure: ""